---
server:
  port: 8888
security:
  user:
    name: murat
    password: murat
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/aykanatm/spring-cloud-config-server-tutorial
          search-paths:
            - 'station*'
          repos:
            perf:
              pattern:
                - "*/perf"
              uri: https://github.com/aykanatm/spring-cloud-config-server-tutorial-perf
              search-paths:
               - 'station*'